### PR TITLE
fix fetch and checksum error on new packer

### PR DESCRIPTION
**Pull request by BenGardiner**
(but still won't build for me)

this _might_ be good enough for the minimum changes requested in #45

### CODE REVIEW

**Comment by bastibl** [comment]
This seems to get us one step further. I tried several hours to get the base installation going to no avail. I don't even know if the problem is packer, virtualbox, or subiquity... I tried several combinations of workarounds but no chance :-/

**Comment by BenGardiner** [comment]
thanks for letting me know @bastibl -- it helps alot to know the problem isn't necessarily on my end !

I've done a bunch of attempts here. Including moving the packer json to a vagrant file and starting with generic/ubutunXX

vagrant version has the advantage that I can pass the ssh step but all ubuntu versions I tried fails with checksum mismatches.

**Comment by BenGardiner** [comment]
now both packer builds work when invoked via `make` on updated and upgraded 21.10 ubuntu machine:

```
$ sh configure                                             
                                                                                                    
Checking for wget (tested with 1.17.1)                                                              
GNU Wget 1.21 built on linux-gnu.                                                                   
                                                                                                    
-cares +digest -gpgme +https +ipv6 +iri +large-file -metalink +nls                                  
+ntlm +opie +psl +ssl/openssl                                                                       
                                                                                                    
Wgetrc:                                                                                             
    /etc/wgetrc (system)                                                                            
Locale:                                                                                             
    /usr/share/locale                                                                               
Compile:                                                                                            
    gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/etc/wgetrc"                                               
    -DLOCALEDIR="/usr/share/locale" -I. -I../../src -I../lib                                        
    -I../../lib -Wdate-time -D_FORTIFY_SOURCE=2 -DHAVE_LIBSSL -DNDEBUG                              
    -g -O2 -ffile-prefix-map=/build/wget-OM48Vs/wget-1.21=.                                         
    -fstack-protector-strong -Wformat -Werror=format-security                                       
    -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall                                                      
Link:                                                                                               
    gcc -DHAVE_LIBSSL -DNDEBUG -g -O2                                                               
    -ffile-prefix-map=/build/wget-OM48Vs/wget-1.21=.                                                
    -fstack-protector-strong -Wformat -Werror=format-security                                       
    -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall -Wl,-Bsymbolic-functions                             
    -Wl,-z,relro -Wl,-z,now -lpcre2-8 -luuid -lidn2 -lssl -lcrypto -lz                              
    -lpsl ftp-opie.o openssl.o http-ntlm.o ../lib/libgnu.a                                          
                                                                                                    
Copyright (C) 2015 Free Software Foundation, Inc.                                                   
License GPLv3+: GNU GPL version 3 or later                                                          
<http://www.gnu.org/licenses/gpl.html>.                                                             
This is free software: you are free to change and redistribute it.                                  
There is NO WARRANTY, to the extent permitted by law.                                               
                                                                                                    
Originally written by Hrvoje Niksic <hniksic@xemacs.org>.                                           
Please send bug reports and questions to <bug-wget@gnu.org>.                                        
                                                                                                    
Checking for HashiCorp Packer (tested with 1.2.1)                                                   
1.6.6                                                                                               
                                                                                                    
Checking for Oracle VM VirtualBox (tested with 5.2.8)                                               
6.1.32_Ubuntur149290                                                                                
                                                                                                    
Checking for Oracle VM VirtualBox Extension Pack (tested with 5.2.8)                                
Pack no. 1:   Oracle VM VirtualBox Extension Pack                                                   
                                                                                                    
Great! Looks like all dependencies are installed. You can go ahead and type 'make' to build the VM. 
```

**Comment by bastibl** [comment]
This is strange. I also have an up-to-date Ubuntu 21.10 system and tested with the packer from the main repo and a more recent version from their PPA. Virtualbox is the same. For me, it hangs during subiquity installation when it tries to download and apply security updates. Do you have any ideas?

**Comment by bastibl** [comment]
Looks like something timed-out after >30min and the build continued. Then got another bug with the more recent packer version. After downgrading it worked. What a SW ecosystem :-) Thank you for the PR!

**Pull request merged**
