### PR TITLE
Fix the deprecated syntax iso_checksum error

### LINKED ISSUE #44: Deprecated configuration key: 'iso_checksum_type'.
When running `make` I get this error:

`Deprecated configuration key: 'iso_checksum_type'. Please call `packer fix`
against your template to update your template to be compatible with the current
version of Packer. Visit https://www.packer.io/docs/commands/fix/ for more
detail.
`

`
packer --version
1.8.0
`

### PR DESCRIPTION
**Pull request by stkrzysiak**
This is the result of running `packer fix base.json`. Unfortunately packer fixed a lot more than the original deprecated field(`iso_checksum_type`).  I can resubmit this PR just fixing the field name only but I figure packer wants this format.  Closes #44

### CODE REVIEW

**Comment by bastibl** [comment]
Looks like this needs more updates or does the build work for you with just this change? For me, it seems to point to an outdated iso.

**Comment by stkrzysiak** [comment]
I was going to update the iso in a different branch, can do it in this one if you prefer?  Even then I run into another issue I was going to tackle in another PR, just thought I'd get the contribution ball rolling.

**Comment by bastibl** [comment]
At the moment, I have no way to test. It would be great, if you could update to a point that it builds again. Everything else can be handled is separate/follow-up PR.

**Comment by stkrzysiak** [comment]
This still errors on a curtin cmd-in-target step, seems to be something introduced in the later versions of 20.04.1+. There seem to be efforts to fix this but upgrading to 21.04 breaks the install automation so not sure how valid the fix is. Will circle back.

https://stackoverflow.com/questions/67457987/ubuntu-server-installation-stops-at-curtin-command-in-target
https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1875560

**Comment by bastibl** [comment]
Looks like we have a working build again. Let me know if there are further issues.

**Comment by stkrzysiak** [comment]
Roger that @bastibl

**Pull request closed without merging**
